import os
import django
import shutil
import urllib.parse
import urllib.request
from pathlib import Path
from PIL import Image

# Setup Django Environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'desibazaar.settings')
django.setup()

from store.models import Product

# Current brain directory
brain_dir = Path(r"C:\Users\vishw\.gemini\antigravity-ide\brain\fd0d2602-a615-4819-9d5f-2f7c340a1172")
media_dir = Path(r"c:\Users\vishw\OneDrive\Documents\Desktop\DesiBazaar\media\products")
media_dir.mkdir(parents=True, exist_ok=True)

# 1. Map of already generated images using the generate_image tool
local_images = {
    41: "rajasthani_wall_hanging_1780550889825.png",
    42: "bidriware_pen_stand_1780550906526.png",
    43: "shilajit_resin_1780550924592.png",
    44: "moringa_leaf_powder_1780550941880.png",
    45: "brass_handi_1780550960146.png",
    46: "wooden_rolling_pin_board_1780550974989.png",
    47: "bangalore_nippattu_1780550989367.png",
    49: "kodubale_1780551008334.png",
    50: "murukku_1780551022251.png",
    54: "ikat_stole_1780551038214.png",
    55: "pashmina_shawl_1780551052185.png",
    57: "jute_carry_bags_1780551069041.png",
    58: "coconut_shell_bowls_1780551082560.png",
    59: "macrame_wall_art_1780551097006.png",
    60: "scented_soy_candles_1780551116942.png",
    61: "handmade_paper_journal_1780551132129.png",
    63: "marble_ganesha_idol_1780551149823.png"
}

# 2. Wikipedia URLs for the remaining 5 products
wiki_images = {
    65: ("copper_water_bottle.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Multi-use_water_bottle.JPG/960px-Multi-use_water_bottle.JPG"),
    66: ("neem_wood_comb.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/960px-Neem_Tree_in_Rajasthan%2C_India.jpg"),
    69: ("masala_chai_premix.jpg", "https://upload.wikimedia.org/wikipedia/commons/8/89/Chai_In_Sakora.jpg"),
    74: ("soapnut_reetha_powder.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Sapindus_mukorossi2.jpg/960px-Sapindus_mukorossi2.jpg"),
    76: ("dhokla_steamer_set.jpg", "https://upload.wikimedia.org/wikipedia/commons/6/65/Dhokla_on_Gujrart.jpg")
}

def download_and_convert_to_png(url, temp_jpg_path, dest_png_path):
    print(f"Downloading from Wikipedia: {url}...")
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    req = urllib.request.Request(url, headers=headers)
    
    # Download JPG
    with urllib.request.urlopen(req, timeout=15) as response:
        with open(temp_jpg_path, 'wb') as out_file:
            out_file.write(response.read())
            
    # Convert to PNG using Pillow
    print(f"Converting {temp_jpg_path.name} to PNG...")
    with Image.open(temp_jpg_path) as img:
        img.save(dest_png_path, "PNG")

def main():
    updated_products = []

    # Process local images
    print("Processing local images generated by tool...")
    for pid, filename in local_images.items():
        src_path = brain_dir / filename
        if not src_path.exists():
            print(f"Warning: Local file not found for ID {pid}: {src_path}")
            continue
            
        dest_filename = f"prod_{pid}.png"
        dest_path = media_dir / dest_filename
        
        # Copy to media directory
        shutil.copy2(src_path, dest_path)
        
        # Update database
        p = Product.objects.get(id=pid)
        p.image_url = f"/media/products/{dest_filename}"
        p.save()
        updated_products.append(pid)
        print(f"Updated product {pid} ({p.name}) with local image.")

    # Process Wikipedia images
    print("\nProcessing remaining images using Wikipedia...")
    for pid, (filename, url) in wiki_images.items():
        temp_jpg = brain_dir / filename
        dest_filename = f"prod_{pid}.png"
        dest_png_path = media_dir / dest_filename
        
        try:
            # Download and convert
            download_and_convert_to_png(url, temp_jpg, dest_png_path)
            
            # Update database
            p = Product.objects.get(id=pid)
            p.image_url = f"/media/products/{dest_filename}"
            p.save()
            updated_products.append(pid)
            print(f"Updated product {pid} ({p.name}) with Wikipedia image converted to PNG.")
        except Exception as e:
            print(f"Error downloading/converting image for product {pid}: {e}")

    # Cleanup alternative file formats (.jpg, .jpeg, .webp) in media dir for all 22 products
    print("\nCleaning up alternative file formats...")
    for pid in list(local_images.keys()) + list(wiki_images.keys()):
        for ext in ['.jpg', '.jpeg', '.webp']:
            alt_file = media_dir / f"prod_{pid}{ext}"
            if alt_file.exists():
                alt_file.unlink()
                print(f"Deleted old file: {alt_file.name}")

    print(f"\nIntegration complete. Successfully updated {len(updated_products)}/22 products.")

if __name__ == '__main__':
    main()
