# All 83 products needing AI-generated images
# Quota resets at ~5:32 PM IST (12:02 UTC) on 2026-06-03
# Run generate_all_images.py after that time

PRODUCTS = [
    (1,   "Mango Pickle",                   "A glass jar of authentic Indian mango pickle with baby mangoes in mustard oil and spices, vibrant yellow-orange, rustic wooden background, professional food photography."),
    (2,   "Kashmiri Saffron",               "Premium Kashmiri saffron strands in a small ornate silver bowl, deep red-orange color, dark moody background, luxury spice product photography."),
    (3,   "Darjeeling First Flush Tea",     "A glass teacup of pale golden Darjeeling first flush tea with fresh green tea leaves beside it, misty hills background, serene morning photography."),
    (4,   "Madhubani Painting",             "A detailed, colorful traditional Madhubani painting on handmade paper with birds, fish, and floral motifs in red, black and earthy tones, close-up showing texture."),
    (5,   "Coorg Arabica Coffee",           "Freshly roasted whole Arabica coffee beans in a rustic burlap sack with a steaming black coffee cup beside it, lush green Coorg plantation background."),
    (6,   "Banarasi Silk Dupatta",          "A luxurious deep red Banarasi silk dupatta with gold zari brocade patterns, draped elegantly on a polished wooden surface, premium textile product photography."),
    (7,   "Mysore Sandalwood Soap",         "A handcrafted pale yellow Mysore Sandalwood soap bar with sandalwood chips and powder beside it, creamy spa aesthetic, clean white background."),
    (8,   "Kerala Coconut Oil",             "A glass bottle of pure white Kerala coconut oil with fresh coconut halves and green coconut leaves beside it, tropical natural product photography."),
    (9,   "Assam CTC Tea",                  "Dark reddish-brown Assam CTC tea granules in a wooden bowl next to a steaming cup of strong milk tea, warm earthy tones, tea garden ambiance."),
    (10,  "Channapatna Wooden Toys",        "A colorful set of hand-painted Channapatna lacquerware wooden toys in red, green and yellow, arranged on a wooden surface, bright cheerful Indian craft photography."),
    (11,  "Amla Murabba",                   "Shiny golden-brown Indian gooseberry (amla) murabba pieces in a glass jar with syrup, close-up showing the texture and shine, warm food photography."),
    (12,  "Blue Pottery Vase",              "An elegant Jaipur Blue Pottery vase with intricate blue and white floral patterns on a pale background, artisan Indian ceramics product photography."),
    (13,  "Bhavnagari Gathiya",             "Crispy golden Bhavnagari gathiya (Gujarati snack) piled in a traditional brass plate with green chutney on the side, warm inviting food photography."),
    (14,  "Shilpakar Dokra Metal Art",      "An intricate Dokra lost-wax cast metal art figurine of a tribal woman carrying a pot, antique golden-brass finish, black background, Indian tribal art photography."),
    (15,  "Shahi Tukda Mix",               "Creamy rich Shahi Tukda dessert - fried bread topped with saffron rabri and garnished with pistachios and rose petals in a silver bowl, royal Indian dessert photography."),
    (16,  "Premium Cashews",               "A pile of whole premium white cashew nuts spilling from a burlap sack onto a wooden table, warm studio lighting, dry fruits product photography."),
    (17,  "Patchwork Kantha Quilt",        "A colorful hand-stitched Kantha quilt with vibrant geometric patchwork patterns in red, blue and yellow cotton fabric, draped over a bed, artisan textile photography."),
    (18,  "Ashwagandha Root Powder",       "Fine beige Ashwagandha root powder in a wooden bowl beside dried ashwagandha roots and leaves, earthy natural Ayurvedic product photography."),
    (19,  "Bamboo Toothbrush Set",         "A set of four natural bamboo toothbrushes with charcoal bristles standing in a ceramic holder, eco-friendly bathroom product photography, clean white background."),
    (20,  "Lac Bangle Set",               "A set of vibrant handcrafted Lac bangles in red and gold with intricate inlay work, arranged on a dark velvet surface, traditional Indian jewelry photography."),
    (21,  "Guntur Red Chilli Powder",      "Vibrant red Guntur chilli powder in a wooden bowl with whole dried red chillies beside it on a rustic dark surface, bold spice product photography."),
    (22,  "Cinnamon Sticks (Ceylon)",      "A bundle of thin fragrant Ceylon cinnamon quills tied with twine beside cinnamon powder in a small bowl on a white surface, premium spice photography."),
    (23,  "Cardamom Pods (Green)",         "Fresh bright green cardamom pods arranged in a small ceramic bowl with a few open pods showing black seeds, clean white background, spice product photography."),
    (24,  "Turmeric Powder (Lakadong)",    "Bright golden-yellow Lakadong turmeric powder in a bowl with fresh turmeric root beside it on a dark slate surface, vibrant Ayurvedic spice photography."),
    (26,  "Mamra Almonds",                "A pile of thin-shelled Mamra almonds from Iran/Kashmir in a silver bowl on a wooden surface, premium dry fruit product photography, warm lighting."),
    (27,  "Medjool Dates",                "Large plump Medjool dates arranged in a date palm leaf basket, warm golden-brown tones, Middle Eastern food styling on a dark wooden surface."),
    (28,  "Walnuts (Kashmiri)",           "Whole and halved Kashmiri walnuts showing rich brown shells and light-colored kernels, arranged on a burlap cloth, warm premium dry fruit photography."),
    (29,  "Raisins (Sultana)",            "Plump golden sultana raisins spilling from a small wooden bowl, warm amber tones on a light wooden surface, premium dry fruit product photography."),
    (30,  "A2 Cow Ghee",                 "A golden glass jar of pure A2 cow ghee with a spoonful showing its rich golden color, small brass diya beside it, warm Indian kitchen ambiance photography."),
    (31,  "Organic Jaggery",             "Rough chunks and a block of dark golden organic jaggery in a rustic clay bowl, sugarcane stalks beside it, warm earthy natural food photography."),
    (32,  "Wild Forest Honey",           "A glass jar of dark amber raw wild forest honey with dripping honey from a wooden dipper, comb fragment beside it, warm rustic natural product photography."),
    (33,  "Kondapalli Bomma Set",        "A set of colorful hand-painted Kondapalli wooden toy figurines of villagers and animals in bright primary colors, arranged on a white surface, traditional Indian craft photography."),
    (34,  "Warli Painting Canvas",       "A white canvas with black and white minimalist Warli tribal art depicting a village dance scene, human stick figures in circular patterns, Indian folk art photography."),
    (35,  "Brass Puja Diya Set",         "A set of three ornate brass puja diyas (oil lamps) with flickering flames, surrounded by marigold petals and incense smoke, warm devotional ambiance photography."),
    (36,  "Phulkari Cushion Cover",      "A vibrant Punjabi Phulkari embroidered cushion cover in bright orange with multicolored floral thread work, displayed on a wooden chair, Indian textile photography."),
    (37,  "Triphala Churna",             "Fine herbal Triphala churna powder in a wooden bowl with three dried amla, haritaki and bibhitaki fruits beside it, Ayurvedic product photography on a dark background."),
    (38,  "Brahmi Hair Oil",             "A dark glass bottle of Brahmi hair oil with fresh green brahmi leaves and coconut beside it, Ayurvedic hair care product photography on a natural stone surface."),
    (39,  "Neem Tulsi Face Wash",        "A green herbal face wash bottle with fresh neem leaves and tulsi basil sprigs beside it, clean fresh organic skincare product photography on a white background."),
    (40,  "Terracotta Flower Pot",       "A handcrafted red terracotta flower pot with a small flowering plant inside, natural clay texture showing fingerprints of the potter, warm earthy product photography."),
    (41,  "Rajasthani Wall Hanging",     "A colorful Rajasthani tapestry wall hanging with mirror work, elephant motifs, and vibrant embroidery in red, orange and gold, displayed against a white wall."),
    (42,  "Bidriware Pen Stand",         "An elegant Bidriware pen stand with silver inlay floral patterns on dark zinc-alloy body, artisan craft product photography on a dark surface with soft lighting."),
    (43,  "Shilajit Resin",             "A small jar of dark black Shilajit resin with a wooden spatula scooping some out, rocky Himalayan mountain backdrop, premium Ayurvedic supplement photography."),
    (44,  "Moringa Leaf Powder",         "Fine bright green Moringa leaf powder in a wooden bowl with fresh Moringa drumstick leaves beside it, clean natural superfood product photography."),
    (45,  "Brass Handi (Cooking Pot)",   "A gleaming brass handi cooking pot with a domed lid, placed on a rustic kitchen surface with spices around it, traditional Indian cookware product photography."),
    (46,  "Wooden Rolling Pin & Board",  "A carved wooden belan (rolling pin) and chakla (rolling board) set with a rolled chapati roti on it, traditional Indian kitchen photography, warm earthy tones."),
    (47,  "Bangalore Nippattu",          "Crispy golden Bangalore nippattu rice crackers stacked in a traditional brass plate with roasted peanuts scattered around, South Indian snack food photography."),
    (48,  "Rajkot Khakhra",             "A stack of thin crispy Rajkot khakhra flatbreads with masala coating, tied with a ribbon, Gujarati snack product photography on a wooden surface."),
    (49,  "Kodubale",                   "Crispy ring-shaped Karnataka kodubale snacks (rice flour rings) piled in a traditional bowl with curry leaves and red chilli, South Indian snack photography."),
    (50,  "Murukku (Rice & Urad)",       "Crispy spiral South Indian murukku chakli snacks in a brass bowl, golden brown with sesame seeds, traditional Indian snack product photography."),
    (51,  "Mysore Pak",                 "Rich golden cubes of Mysore Pak (ghee-chickpea flour fudge) in a silver tray, crumbly texture visible, South Indian mithai food photography."),
    (52,  "Kaju Katli",                 "Diamond-shaped silver-foil topped Kaju Katli (cashew fudge) arranged on a royal blue surface, Indian festive sweet product photography."),
    (53,  "Mathura Peda",               "Round golden-brown Mathura peda milk sweets dusted with cardamom powder in a traditional clay pot, Indian mithai product photography, warm golden lighting."),
    (54,  "Ikat Stole",                 "A colorful Ikat hand-woven stole with geometric diamond patterns in indigo, red and white, draped elegantly, Indian handloom textile photography."),
    (55,  "Pashmina Shawl",             "A luxuriously soft pure Pashmina shawl in natural cream color with intricate paisley border embroidery, draped softly, premium Kashmiri textile photography."),
    (57,  "Jute Carry Bags (Set of 5)",  "A set of five natural burlap jute carry bags in different sizes with cotton handles, arranged neatly, eco-friendly Indian handicraft product photography."),
    (58,  "Coconut Shell Bowl Set",     "A set of three polished dark coconut shell bowls of different sizes, arranged on a bamboo mat, natural eco-friendly kitchen product photography."),
    (59,  "Handmade Macrame Wall Art",  "A handcrafted boho macrame wall hanging with intricate knotted patterns and fringe, cream cotton rope, displayed on a light wall, artisan decor photography."),
    (60,  "Scented Soy Candles (Set of 3)", "Three elegant scented soy wax candles in marble ceramic vessels with different heights, jasmine and sandalwood fragrance, luxury home decor product photography."),
    (61,  "Handmade Paper Journal",     "A handmade paper journal with a hand-stitched cotton cover, block-printed floral design, handmade paper pages visible, artisan stationery product photography."),
    (62,  "Brass Pen (Handturned)",     "An elegant hand-turned solid brass ballpoint pen with engraved floral patterns, displayed on a leather writing pad, premium artisan writing instrument photography."),
    (63,  "Ganesha Idol (White Marble)", "A beautifully carved Lord Ganesha idol in pure white marble with gold accents and detailed craftsmanship, placed on a wooden altar, serene soft studio lighting."),
    (64,  "Pattachitra Cloth Painting", "A traditional Odisha Pattachitra painting on cloth depicting mythological scenes with intricate borders, vivid natural colors, Indian folk art closeup photography."),
    (65,  "Copper Water Bottle",        "A sleek hammered pure copper water bottle with lid on a wooden surface with water droplets, Ayurvedic wellness product photography, warm natural lighting."),
    (66,  "Neem Wood Comb",             "A wide-tooth natural neem wood comb with smooth teeth on a soft white towel beside a green neem leaf, minimalist organic hair care product photography."),
    (68,  "Kolhapuri Chappal",          "A pair of handcrafted tan leather Kolhapuri sandals with intricate woven strap designs, placed on a woven jute mat, traditional Indian footwear photography."),
    (69,  "Masala Chai Premix",         "A steaming terracotta cup of creamy masala chai with cardamom, cinnamon and ginger sticks beside it, cozy Indian kitchen atmosphere, warm food photography."),
    (70,  "Nilgiri Green Tea",          "A glass cup of clear pale green Nilgiri tea with fresh green tea leaves in a bamboo strainer beside it, misty Nilgiri hills backdrop, serene tea photography."),
    (71,  "Bamboo Rice",               "A small open burlap sack of greenish-white bamboo rice grains with bamboo stalks beside it, rustic wooden surface, exotic grain product photography."),
    (73,  "Gond Katira",               "Translucent golden-amber crystals of Gond Katira tragacanth gum in a glass bowl with some soaked gel beside it, natural Ayurvedic ingredient photography."),
    (74,  "Soapnut (Reetha) Powder",   "Fine brown Reetha soapnut powder in a wooden bowl with dried whole soapnuts scattered around, natural organic hair care product photography on hessian cloth."),
    (75,  "Tanjore Doll Pair",         "A pair of colorful Tanjore bobblehead dolls with gold crowns and bright silk costumes, one male one female, displayed on a polished wooden surface, Indian craft photography."),
    (76,  "Dhokla Steamer Set",        "A stainless steel multi-tier dhokla/idli steamer set with steaming holes, on a modern kitchen counter with steam rising, Indian cookware product photography."),
    (77,  "Pichwai Painting (Lord Krishna)", "A detailed traditional Pichwai painting showing Lord Krishna playing flute surrounded by cows and lotus flowers, rich jewel colors on dark background, Indian sacred art photography."),
    (99,  "Flaxseed Oil",              "An amber glass bottle of cold-pressed golden flaxseed oil with brown flaxseeds scattered beside it on a neutral linen surface, organic health product photography."),
    (100, "Giloy Juice",               "A green glass bottle of herbal Giloy juice with fresh heart-shaped Giloy leaves and stems on a stone surface, natural Ayurvedic wellness product photography."),
    (101, "Aloe Vera Gel",             "A clear glass jar of fresh translucent Aloe Vera gel with cut aloe leaves showing the gel inside, water droplets on white surface, fresh organic skincare photography."),
    (102, "Coconut Shell Ladle Set",   "A set of handcrafted kitchen ladles and spoons made from polished coconut shells with wooden handles, arranged on a rustic wooden board, eco kitchen product photography."),
    (103, "Spice Box (Masala Dabba)",  "An open traditional Indian stainless steel spice box (masala dabba) with 7 small compartments filled with colorful spices, top-down view, vibrant spice photography."),
    (105, "Marigold Agarbatti",        "Handcrafted orange marigold-scented incense sticks in a brass dhoop holder with fresh marigold flowers, thin smoke rising, serene devotional atmosphere photography."),
    (106, "Ghee Rice Mix",             "Aromatic South Indian ghee rice with cashews, raisins and spices in a decorative brass bowl with steam rising, traditional Indian food styling photography."),
    (110, "Indigo Dye Powder",         "Deep blue natural indigo powder in a terracotta bowl with fresh indigo plant branches beside it on white linen, natural dye product photography."),
    (137, "Khadi Notebook Set",        "A set of three handmade Khadi cotton paper notebooks with block-printed covers in earthy tones, tied with a jute string, artisan stationery product photography."),
    (140, "Bhopal Zardozi Pouch",      "A premium handcrafted Bhopal Zardozi embroidered silk pouch with intricate gold thread and bead work on royal blue, luxury Indian handicraft product photography."),
]
